### ISSUE TITLE
text/html response content type not supported

### ISSUE THREAD

**Issue by timijntema** [swagger-mock/swagger-mock#19]
The text/html response content type does not seem to be supported.

Stacktrace:
```
App\Mock\Exception\NotSupportedException: Not supported media type "text/html". in /app/src/API/Responder.php:70
Stack trace:
#0 /app/src/API/Responder.php(56): App\API\Responder->guessSerializationFormat('text/html')
#1 /app/src/API/Responder.php(37): App\API\Responder->encodeDataByMediaType('Dolores illum v...', 'text/html')
#2 /app/src/Mock/MockResponseGenerator.php(65): App\API\Responder->createResponse(200, 'text/html', 'Dolores illum v...')
#3 /app/src/API/RequestHandler.php(43): App\Mock\MockResponseGenerator->generateResponse(Object(Symfony\Component\HttpFoundation\Request), Object(App\Mock\Parameters\Endpoint))
#4 /app/src/EventListener/RequestListener.php(32): App\API\RequestHandler->handleRequest(Object(Symfony\Component\HttpFoundation\Request))
#5 /app/vendor/symfony/event-dispatcher/EventDispatcher.php(298): App\EventListener\RequestListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\RequestEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#6 /app/vendor/symfony/event-dispatcher/EventDispatcher.php(260): Symfony\Component\EventDispatcher\EventDispatcher::Symfony\Component\EventDispatcher\{closure}(Object(Symfony\Component\HttpKernel\Event\RequestEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#7 /app/vendor/symfony/event-dispatcher/EventDispatcher.php(235): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\RequestEvent))
#8 /app/vendor/symfony/event-dispatcher/EventDispatcher.php(75): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\RequestEvent))
#9 /app/vendor/symfony/http-kernel/HttpKernel.php(127): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(Symfony\Component\HttpKernel\Event\RequestEvent), 'kernel.request')
#10 /app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#11 /app/vendor/symfony/http-kernel/Kernel.php(198): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#12 /app/bin/worker.php(48): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
```

**Comment by strider2038** [comment]
@timijntema thank you for issue! Support for "text/html" added in [v0.1.9](https://github.com/swagger-mock/swagger-mock/releases/tag/v0.1.9)
